services:
  freescout-app:
    image: docker.io/nfrastack/freescout:latest
    container_name: freescout-app
    volumes:
      - freescout_data:/data
      - freescout_logs:/www/logs
    environment:
      - TIMEZONE=Europe/Amsterdam
      - CONTAINER_NAME=freescout-app
      - DB_HOST=freescout-db
      - DB_NAME=freescout
      - DB_USER=freescout
      - DB_PASS=freescout
      - SITE_URL=https://jouwdomein.nl
      - ADMIN_EMAIL=admin@jouwdomein.nl
      - ADMIN_PASS=jouwwachtwoord
    depends_on:
      - freescout-db
    restart: always

  freescout-db:
    image: docker.io/mariadb:10.11
    container_name: freescout-db
    volumes:
      - freescout_db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=freescout
      - MYSQL_USER=freescout
      - MYSQL_PASSWORD=freescout
      - MYSQL_ROOT_PASSWORD=rootwachtwoord
    restart: always

volumes:
  freescout_data:
  freescout_logs:
  freescout_db:
